// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'description': string;
  'linkButton': string;
  'modalBody': string;
  'modalContent': string;
  'options': string;
}
export const cssExports: CssExports;
export default cssExports;
