// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'error': string;
  'field': string;
  'help': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
