// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deferContainer': string;
  'importButton': string;
  'importButtonContainer': string;
  'importError': string;
  'importProgress': string;
  'inputContainer': string;
  'label': string;
  'loading': string;
  'loadingButton': string;
}
export const cssExports: CssExports;
export default cssExports;
