// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'option': string;
  'optionDescription': string;
  'optionLabel': string;
  'optionText': string;
  'options': string;
  'pathInfo': string;
  'question': string;
  'radio': string;
}
export const cssExports: CssExports;
export default cssExports;
